one_hot_encoding

In [20]:
import numpy as np
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense

In [3]:
X = np.array(['dog', 'cat', 'bird', 'fish'])

In [4]:
# 라벨 인코더 생성하기
encoder = LabelEncoder()

In [5]:
# 숫자로 변환하기
encoder.fit(X)
y = encoder.transform(X)
print(y)

[2 1 0 3]


In [6]:
# 디코더
print(encoder.inverse_transform([3,2,1,0]))

['fish' 'dog' 'cat' 'bird']


In [8]:
# one_hot_encoding
Y = np_utils.to_categorical(y)
print(y)

[2 1 0 3]


붓꽃(irsi) 데이터셋 로드

In [9]:
import pandas as pd
df = pd.read_csv('/content/iris(150).csv')
df.head()

caseno  SepalLength  SepalWidth  PetalLength  PetalWidth Species
0       1          5.1         3.5          1.4         0.2  setosa
1       2          4.9         3.0          1.4         0.2  setosa
2       3          4.7         3.2          1.3         0.2  setosa
3       4          4.6         3.1          1.5         0.2  setosa
4       5          5.0         3.6          1.4         0.2  setosa

In [14]:
df = df.drop(['caseno'], axis=1)

In [17]:
# X 데이터 할당

data_set = df.values
X = data_set[:, 0:4].astype(float)

# y 데이터 할당
y = data_set[:, 4]

In [18]:
# labelencoder: 수치 변환
encoder = LabelEncoder()
encoder.fit(y)
y_encodered = encoder.transform(y)

In [ ]:
# one_hot_encoding
y = pd.get_dummies(y_encodered).values
print(y)

모델 생성하기

In [21]:
model = Sequential()

model.add(Dense(16, input_dim=4, activation='relu'))
# 출력 노드 16, 입력 노드 4, 활성화 함수 relu
model.add(Dense(3, activation='softmax'))
# 출력 노드 3 (붓꽃의 종류가 3개이므로), 활성화 함수 softmax


모델 구성하기

In [22]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# softmax 활성화 함수를 사용할 때는 loss 함수로 categorical_crossentropy를 사용한다.

모델 학습하기

In [23]:
model.fit(X, y, epochs=100, batch_size=1)


Epoch 1/100
150/150 [==============================] - 15s 1ms/step - loss: 2.2114 - accuracy: 0.3330
Epoch 2/100
150/150 [==============================] - 0s 1ms/step - loss: 1.2436 - accuracy: 0.3724
Epoch 3/100
150/150 [==============================] - 0s 1ms/step - loss: 0.9998 - accuracy: 0.3491
Epoch 4/100
150/150 [==============================] - 0s 1ms/step - loss: 0.7585 - accuracy: 0.6427
Epoch 5/100
150/150 [==============================] - 0s 1ms/step - loss: 0.6316 - accuracy: 0.8597
Epoch 6/100
150/150 [==============================] - 0s 1ms/step - loss: 0.5590 - accuracy: 0.9420
Epoch 7/100
150/150 [==============================] - 0s 1ms/step - loss: 0.5150 - accuracy: 0.8641
Epoch 8/100
150/150 [==============================] - 0s 1ms/step - loss: 0.4696 - accuracy: 0.8341
Epoch 9/100
150/150 [==============================] - 0s 996us/step - loss: 0.4152 - accuracy: 0.9128
Epoch 10/100
150/150 [==============================] - 0s 983us/step - loss: 0.3748 - a

모델 예측하기

In [25]:
model.predict(np.array([[4.7, 3.2, 1.3, 0.2]]))

array([[9.9976724e-01, 2.3271189e-04, 2.6194856e-12]], dtype=float32)